Update to vfs 0.12
Berrysoft/vfs-tar pull request #1
Opened 2024-06-17 20:24 UTC by apps4uco

Just one small thing left to do, add the metadata for mtime, atime and ctime

```
     Running unittests src/lib.rs (target/debug/deps/vfs_tar-1dc0a0c78b239662)

running 4 tests
test test::basic ... ok
test test::long ... ok
test test::ustar ... ok
test test::link ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

```

2024-06-18 23:02 UTC, Berrysoft requested changes
Format the code with rustfmt, please.

2024-06-19 02:09 UTC, apps4uco commented
Sure thing, See efe855562290ff1e9fedfaea809486b1263d8139

2024-06-19 05:54 UTC, Berrysoft approved these changes

2024-06-19 05:55 UTC, Berrysoft approved these changes

2024-06-19 05:55 UTC, merged